"""add_upload_and_order_tables

Revision ID: 2c339af14fba
Revises: 2ee018142088
Create Date: 2026-07-13 17:32:17.684676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c339af14fba'
down_revision: Union[str, Sequence[str], None] = '2ee018142088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('marketplace_detected', sa.String(), nullable=True),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('row_count_raw', sa.Integer(), nullable=True),
    sa.Column('row_count_processed', sa.Integer(), nullable=True),
    sa.Column('row_count_excluded', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fulfilment', sa.String(), nullable=True),
    sa.Column('ship_service_level', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('ship_state', sa.String(), nullable=True),
    sa.Column('ship_city', sa.String(), nullable=True),
    sa.Column('b2b', sa.Boolean(), nullable=True),
    sa.Column('estimated_cogs', sa.Float(), nullable=True),
    sa.Column('platform_fee', sa.Float(), nullable=True),
    sa.Column('shipping_cost', sa.Float(), nullable=True),
    sa.Column('gst', sa.Float(), nullable=True),
    sa.Column('return_loss', sa.Float(), nullable=True),
    sa.Column('estimated_profit', sa.Float(), nullable=True),
    sa.Column('return_flag', sa.Integer(), nullable=True),
    sa.Column('risk_probability', sa.Float(), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('uploads')
    # ### end Alembic commands ###
